# Configuration for Travis CI
# https://travis-ci.org/kongr45gpen/bzflag

language: cpp

before_install:
  - git clone git://github.com/cpputest/cpputest.git
  - cd cpputest/cpputest_build
  - autoreconf .. -i
  - ../configure
  - sudo make install
  - cd ../..

install:
  - ./autogen.sh
  - ./configure
  - make
  - make tests

script:
  - tests/tests
